	<!DOCTYPE html>
	<html>
	<head>
	</head>
	<body>
	<p style="text-align: center;"><span style="font-size: 24pt;"><strong>Vendo Mesa de 5 Patas con 1 Puf incluido</strong></span></p>
	<p style="text-align: center;">&nbsp;</p>
	<table style="width: 391px; margin-left: auto; margin-right: auto;">
	<tbody>
	<tr>
	<td style="width: 204.5px;"><span style="font-size: 24pt;"><strong><img src="http://d26lpennugtm8s.cloudfront.net/stores/100/066/products/_dsc0057-357320622a714bd6ab13e11939f0576f-1024-1024.jpg" alt="" width="223" height="223" /></strong></span></td>
	<td style="width: 190.5px; text-align: justify;">
	<p><span style="font-size: 24pt;"><strong><img style="float: left;" src="http://www.mobicol.com/imatges/productes/tn1_mesa%20quo%205%20patas.jpg" alt="" width="301" height="306" /></strong></span></p>
	</td>
	</tr>
	</tbody>
	</table>
	<p style="text-align: center;"><span style="color: #808080;">Mesa de aluminio innoxidable. con tope de marmol, y pies de silicon, dando confort a los visitantes, adicionalmente le rematamos un puff para utilizar</span> <span style="font-size: 14pt; font-family: georgia,palatino,serif;">con la mesa o lo que quieran.</span><br /><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; color: blue; font-size: 20pt;"><em><em><strong><strong><span style="font-size: large;"><strong><em><em><strong><span style="font-size: medium;"><span style="font-family: Times New Roman;"><strong><span style="font-size: large;"><em><em><strong><span style="font-size: medium;"><span style="font-family: Times New Roman;"><span style="font-size: large;"><span style="font-size: medium;"><span style="font-size: large;"><em><strong><span style="font-size: medium;"><strong><em><span style="color: #800080;"><strong><strong><strong><strong><strong><strong><strong><strong><span style="font-size: medium;"><strong><em><span style="color: #800080;"><strong><strong><strong><strong><strong><strong><strong><strong><span style="font-size: medium;"><span style="font-size: large;"><strong><em><em><strong><span style="font-size: medium;"><span style="font-family: Times New Roman;"><strong><em><strong><em><em><strong><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; color: green; font-size: 13.5pt;"><strong><em><span style="font-size: medium;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; color: purple; font-size: 13.5pt;"><span style="color: #000080;">ofrecemos la posibilidad de resguardar sus compras, <br />hasta consolidar la cantidad necesaria de art&iacute;culos a su elecci&oacute;n, <br />para disminuir su costo operativo en los env&iacute;os<br /></span></span></em></strong></span></em></strong></span></strong></em></em></strong></em></strong></span></span></strong></em></em></strong></span></span></strong></strong></strong></strong></strong></strong></strong></strong></span></em></strong></span></strong></strong></strong></strong></strong></strong></strong></strong></span></em></strong></span></strong></em></span></span></span></span></span></strong></em></em></span></strong></span></span></strong></em></em></strong></span></strong></strong></em></em></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;" align="center"><span style="color: #888888;"><span style="font-size: medium;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';">emitido por: banco central de venezuela</span></em></strong></span></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;" align="center"><span style="font-size: medium; color: #888888;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';">fabricante: the de la rue company, inglaterra</span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;" align="center"><span style="font-size: medium; color: #888888;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';"><span style="color: #888888;"><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; font-size: 20pt;"><span style="font-size: large;"><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; font-size: 20pt;"><span style="font-variant: small-caps;"><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; font-size: 14pt;"><span style="font-family: 'Comic Sans MS';"><strong><em><span style="font-variant: small-caps; font-family: 'Carolingia (BigfooT)'; font-size: 24pt;"><strong><span style="font-variant: small-caps; font-family: 'Carolingia (BigfooT)'; font-size: 22pt;"><em><em><strong><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; font-size: 13.5pt;"><span style="font-variant: small-caps;"><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; font-size: 14pt;"><span style="font-family: 'Comic Sans MS';"><em><span style="font-variant: small-caps; font-family: 'Carolingia (BigfooT)'; font-size: 24pt;"><span style="font-size: medium;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';">cantidad emitida: 6.000.000 de billetes</span></em></strong></span></span></em></span></span></span></span></strong></em></em></span></strong></span></em></strong></span></span></span></span></span></span></span></span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;" align="center"><span style="font-size: medium; color: #888888;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';"><span style="color: #888888;"><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; font-size: 20pt;"><span style="font-size: large;"><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; font-size: 20pt;"><span style="font-variant: small-caps;"><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; font-size: 14pt;"><span style="font-family: 'Comic Sans MS';"><strong><em><span style="font-variant: small-caps; font-family: 'Carolingia (BigfooT)'; font-size: 24pt;"><strong><span style="font-variant: small-caps; font-family: 'Carolingia (BigfooT)'; font-size: 22pt;"><em><em><strong><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; font-size: 13.5pt;"><span style="font-variant: small-caps;"><span style="font-variant: small-caps; font-family: 'Comic Sans MS'; font-size: 14pt;"><span style="font-family: 'Comic Sans MS';"><em><span style="font-variant: small-caps; font-family: 'Carolingia (BigfooT)'; font-size: 24pt;"><span style="font-size: medium;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';">&nbsp;</span></em></strong></span></span></em></span></span></span></span></strong></em></em></span></strong></span></em></strong></span></span></span></span></span></span></span></span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;" align="center"><span style="font-size: medium; color: #888888;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';">combinaci&oacute;n de firmas:</span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;" align="center"><span style="font-size: medium; color: #888888;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';">presidente / vice-presidente</span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;" align="center"><span style="font-size: medium; color: #888888;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';">alfredo lafee / carlos rafael silva<br /></span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;" align="center"><span style="font-size: medium;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';">&nbsp;</span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;" align="center"><span style="font-size: medium;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';"><span style="color: #000080;">condici&oacute;n: FINE-</span><br /><span style="color: #000080;">el billete presenta: dobleces. ondulaciones y manchas acordes al estado de conservaci&oacute;n.</span></span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;" align="center"><span style="font-size: medium;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';"><span style="color: #000080;">regular consistencia de papel.<br /></span></span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;"><span style="color: #808080;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';"><span style="font-size: medium;">&nbsp;</span></span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;"><span style="color: #808080;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';"><span style="font-size: medium;">tipo F, seg&uacute;n clasificaci&oacute;n del libro </span></span></em></strong></span></p>
	<p style="text-align: center; margin: 0cm 0cm 0pt;"><span style="color: #808080;"><strong><em><span style="font-variant: small-caps; font-family: 'Comic Sans MS';"><span style="font-size: medium;">"los billetes del banco central de venezuela" de sergio sucre castillo</span></span></em></strong></span></p>
	<p style="text-align: center;">&nbsp;</p>
	</body>
	</html>